/*
 * Account Management Service API
 * Manage user subscriptions and clusters
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.redhat.services.ffm.amsclient.models;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * CloudResourceAllOf
 */
@JsonPropertyOrder({
  CloudResourceAllOf.JSON_PROPERTY_ACTIVE,
  CloudResourceAllOf.JSON_PROPERTY_CATEGORY,
  CloudResourceAllOf.JSON_PROPERTY_CATEGORY_PRETTY,
  CloudResourceAllOf.JSON_PROPERTY_CLOUD_PROVIDER,
  CloudResourceAllOf.JSON_PROPERTY_CPU_CORES,
  CloudResourceAllOf.JSON_PROPERTY_CREATED_AT,
  CloudResourceAllOf.JSON_PROPERTY_GENERIC_NAME,
  CloudResourceAllOf.JSON_PROPERTY_MEMORY,
  CloudResourceAllOf.JSON_PROPERTY_MEMORY_PRETTY,
  CloudResourceAllOf.JSON_PROPERTY_NAME_PRETTY,
  CloudResourceAllOf.JSON_PROPERTY_RESOURCE_TYPE,
  CloudResourceAllOf.JSON_PROPERTY_SIZE_PRETTY,
  CloudResourceAllOf.JSON_PROPERTY_UPDATED_AT
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-04-21T14:46:15.841437+02:00[Europe/Prague]")
public class CloudResourceAllOf {
  public static final String JSON_PROPERTY_ACTIVE = "active";
  private Boolean active = true;

  public static final String JSON_PROPERTY_CATEGORY = "category";
  private String category;

  public static final String JSON_PROPERTY_CATEGORY_PRETTY = "category_pretty";
  private String categoryPretty;

  public static final String JSON_PROPERTY_CLOUD_PROVIDER = "cloud_provider";
  private String cloudProvider;

  public static final String JSON_PROPERTY_CPU_CORES = "cpu_cores";
  private Integer cpuCores;

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_GENERIC_NAME = "generic_name";
  private String genericName;

  public static final String JSON_PROPERTY_MEMORY = "memory";
  private Integer memory;

  public static final String JSON_PROPERTY_MEMORY_PRETTY = "memory_pretty";
  private String memoryPretty;

  public static final String JSON_PROPERTY_NAME_PRETTY = "name_pretty";
  private String namePretty;

  /**
   * Gets or Sets resourceType
   */
  public enum ResourceTypeEnum {
    ADDON("addon"),
    
    COMPUTE_NODE("compute.node"),
    
    CLUSTER("cluster"),
    
    NETWORK_IO("network.io"),
    
    NETWORK_LOADBALANCER("network.loadbalancer"),
    
    PV_STORAGE("pv.storage");

    private String value;

    ResourceTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ResourceTypeEnum fromValue(String value) {
      for (ResourceTypeEnum b : ResourceTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_RESOURCE_TYPE = "resource_type";
  private ResourceTypeEnum resourceType;

  public static final String JSON_PROPERTY_SIZE_PRETTY = "size_pretty";
  private String sizePretty;

  public static final String JSON_PROPERTY_UPDATED_AT = "updated_at";
  private OffsetDateTime updatedAt;

  public CloudResourceAllOf() { 
  }

  public CloudResourceAllOf active(Boolean active) {
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ACTIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getActive() {
    return active;
  }


  @JsonProperty(JSON_PROPERTY_ACTIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActive(Boolean active) {
    this.active = active;
  }


  public CloudResourceAllOf category(String category) {
    this.category = category;
    return this;
  }

   /**
   * Get category
   * @return category
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CATEGORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCategory() {
    return category;
  }


  @JsonProperty(JSON_PROPERTY_CATEGORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCategory(String category) {
    this.category = category;
  }


  public CloudResourceAllOf categoryPretty(String categoryPretty) {
    this.categoryPretty = categoryPretty;
    return this;
  }

   /**
   * Get categoryPretty
   * @return categoryPretty
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CATEGORY_PRETTY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCategoryPretty() {
    return categoryPretty;
  }


  @JsonProperty(JSON_PROPERTY_CATEGORY_PRETTY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCategoryPretty(String categoryPretty) {
    this.categoryPretty = categoryPretty;
  }


  public CloudResourceAllOf cloudProvider(String cloudProvider) {
    this.cloudProvider = cloudProvider;
    return this;
  }

   /**
   * Get cloudProvider
   * @return cloudProvider
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CLOUD_PROVIDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCloudProvider() {
    return cloudProvider;
  }


  @JsonProperty(JSON_PROPERTY_CLOUD_PROVIDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCloudProvider(String cloudProvider) {
    this.cloudProvider = cloudProvider;
  }


  public CloudResourceAllOf cpuCores(Integer cpuCores) {
    this.cpuCores = cpuCores;
    return this;
  }

   /**
   * Get cpuCores
   * @return cpuCores
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CPU_CORES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getCpuCores() {
    return cpuCores;
  }


  @JsonProperty(JSON_PROPERTY_CPU_CORES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCpuCores(Integer cpuCores) {
    this.cpuCores = cpuCores;
  }


  public CloudResourceAllOf createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public CloudResourceAllOf genericName(String genericName) {
    this.genericName = genericName;
    return this;
  }

   /**
   * Get genericName
   * @return genericName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_GENERIC_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGenericName() {
    return genericName;
  }


  @JsonProperty(JSON_PROPERTY_GENERIC_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGenericName(String genericName) {
    this.genericName = genericName;
  }


  public CloudResourceAllOf memory(Integer memory) {
    this.memory = memory;
    return this;
  }

   /**
   * Get memory
   * @return memory
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MEMORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMemory() {
    return memory;
  }


  @JsonProperty(JSON_PROPERTY_MEMORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMemory(Integer memory) {
    this.memory = memory;
  }


  public CloudResourceAllOf memoryPretty(String memoryPretty) {
    this.memoryPretty = memoryPretty;
    return this;
  }

   /**
   * Get memoryPretty
   * @return memoryPretty
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MEMORY_PRETTY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMemoryPretty() {
    return memoryPretty;
  }


  @JsonProperty(JSON_PROPERTY_MEMORY_PRETTY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMemoryPretty(String memoryPretty) {
    this.memoryPretty = memoryPretty;
  }


  public CloudResourceAllOf namePretty(String namePretty) {
    this.namePretty = namePretty;
    return this;
  }

   /**
   * Get namePretty
   * @return namePretty
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NAME_PRETTY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNamePretty() {
    return namePretty;
  }


  @JsonProperty(JSON_PROPERTY_NAME_PRETTY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNamePretty(String namePretty) {
    this.namePretty = namePretty;
  }


  public CloudResourceAllOf resourceType(ResourceTypeEnum resourceType) {
    this.resourceType = resourceType;
    return this;
  }

   /**
   * Get resourceType
   * @return resourceType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RESOURCE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ResourceTypeEnum getResourceType() {
    return resourceType;
  }


  @JsonProperty(JSON_PROPERTY_RESOURCE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResourceType(ResourceTypeEnum resourceType) {
    this.resourceType = resourceType;
  }


  public CloudResourceAllOf sizePretty(String sizePretty) {
    this.sizePretty = sizePretty;
    return this;
  }

   /**
   * Get sizePretty
   * @return sizePretty
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SIZE_PRETTY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSizePretty() {
    return sizePretty;
  }


  @JsonProperty(JSON_PROPERTY_SIZE_PRETTY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSizePretty(String sizePretty) {
    this.sizePretty = sizePretty;
  }


  public CloudResourceAllOf updatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  /**
   * Return true if this CloudResource_allOf object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CloudResourceAllOf cloudResourceAllOf = (CloudResourceAllOf) o;
    return Objects.equals(this.active, cloudResourceAllOf.active) &&
        Objects.equals(this.category, cloudResourceAllOf.category) &&
        Objects.equals(this.categoryPretty, cloudResourceAllOf.categoryPretty) &&
        Objects.equals(this.cloudProvider, cloudResourceAllOf.cloudProvider) &&
        Objects.equals(this.cpuCores, cloudResourceAllOf.cpuCores) &&
        Objects.equals(this.createdAt, cloudResourceAllOf.createdAt) &&
        Objects.equals(this.genericName, cloudResourceAllOf.genericName) &&
        Objects.equals(this.memory, cloudResourceAllOf.memory) &&
        Objects.equals(this.memoryPretty, cloudResourceAllOf.memoryPretty) &&
        Objects.equals(this.namePretty, cloudResourceAllOf.namePretty) &&
        Objects.equals(this.resourceType, cloudResourceAllOf.resourceType) &&
        Objects.equals(this.sizePretty, cloudResourceAllOf.sizePretty) &&
        Objects.equals(this.updatedAt, cloudResourceAllOf.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(active, category, categoryPretty, cloudProvider, cpuCores, createdAt, genericName, memory, memoryPretty, namePretty, resourceType, sizePretty, updatedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CloudResourceAllOf {\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    categoryPretty: ").append(toIndentedString(categoryPretty)).append("\n");
    sb.append("    cloudProvider: ").append(toIndentedString(cloudProvider)).append("\n");
    sb.append("    cpuCores: ").append(toIndentedString(cpuCores)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    genericName: ").append(toIndentedString(genericName)).append("\n");
    sb.append("    memory: ").append(toIndentedString(memory)).append("\n");
    sb.append("    memoryPretty: ").append(toIndentedString(memoryPretty)).append("\n");
    sb.append("    namePretty: ").append(toIndentedString(namePretty)).append("\n");
    sb.append("    resourceType: ").append(toIndentedString(resourceType)).append("\n");
    sb.append("    sizePretty: ").append(toIndentedString(sizePretty)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

