/*
 * Account Management Service API
 * Manage user subscriptions and clusters
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.redhat.services.ffm.amsclient.models;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.redhat.services.ffm.amsclient.models.ObjectReference;
import com.redhat.services.ffm.amsclient.models.QuotaCostAllOf;
import com.redhat.services.ffm.amsclient.models.RelatedResource;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * QuotaCost
 */
@JsonPropertyOrder({
  QuotaCost.JSON_PROPERTY_HREF,
  QuotaCost.JSON_PROPERTY_ID,
  QuotaCost.JSON_PROPERTY_KIND,
  QuotaCost.JSON_PROPERTY_ALLOWED,
  QuotaCost.JSON_PROPERTY_CONSUMED,
  QuotaCost.JSON_PROPERTY_ORGANIZATION_ID,
  QuotaCost.JSON_PROPERTY_QUOTA_ID,
  QuotaCost.JSON_PROPERTY_RELATED_RESOURCES,
  QuotaCost.JSON_PROPERTY_VERSION
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-04-21T14:46:15.841437+02:00[Europe/Prague]")
public class QuotaCost {
  public static final String JSON_PROPERTY_HREF = "href";
  private String href;

  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_KIND = "kind";
  private String kind;

  public static final String JSON_PROPERTY_ALLOWED = "allowed";
  private Integer allowed;

  public static final String JSON_PROPERTY_CONSUMED = "consumed";
  private Integer consumed;

  public static final String JSON_PROPERTY_ORGANIZATION_ID = "organization_id";
  private String organizationId;

  public static final String JSON_PROPERTY_QUOTA_ID = "quota_id";
  private String quotaId;

  public static final String JSON_PROPERTY_RELATED_RESOURCES = "related_resources";
  private List<RelatedResource> relatedResources = null;

  public static final String JSON_PROPERTY_VERSION = "version";
  private String version;

  public QuotaCost() { 
  }

  public QuotaCost href(String href) {
    this.href = href;
    return this;
  }

   /**
   * Get href
   * @return href
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_HREF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHref() {
    return href;
  }


  @JsonProperty(JSON_PROPERTY_HREF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHref(String href) {
    this.href = href;
  }


  public QuotaCost id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public QuotaCost kind(String kind) {
    this.kind = kind;
    return this;
  }

   /**
   * Get kind
   * @return kind
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_KIND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getKind() {
    return kind;
  }


  @JsonProperty(JSON_PROPERTY_KIND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKind(String kind) {
    this.kind = kind;
  }


  public QuotaCost allowed(Integer allowed) {
    this.allowed = allowed;
    return this;
  }

   /**
   * Get allowed
   * @return allowed
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ALLOWED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getAllowed() {
    return allowed;
  }


  @JsonProperty(JSON_PROPERTY_ALLOWED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAllowed(Integer allowed) {
    this.allowed = allowed;
  }


  public QuotaCost consumed(Integer consumed) {
    this.consumed = consumed;
    return this;
  }

   /**
   * Get consumed
   * @return consumed
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_CONSUMED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getConsumed() {
    return consumed;
  }


  @JsonProperty(JSON_PROPERTY_CONSUMED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setConsumed(Integer consumed) {
    this.consumed = consumed;
  }


  public QuotaCost organizationId(String organizationId) {
    this.organizationId = organizationId;
    return this;
  }

   /**
   * Get organizationId
   * @return organizationId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ORGANIZATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOrganizationId() {
    return organizationId;
  }


  @JsonProperty(JSON_PROPERTY_ORGANIZATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrganizationId(String organizationId) {
    this.organizationId = organizationId;
  }


  public QuotaCost quotaId(String quotaId) {
    this.quotaId = quotaId;
    return this;
  }

   /**
   * Get quotaId
   * @return quotaId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_QUOTA_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getQuotaId() {
    return quotaId;
  }


  @JsonProperty(JSON_PROPERTY_QUOTA_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setQuotaId(String quotaId) {
    this.quotaId = quotaId;
  }


  public QuotaCost relatedResources(List<RelatedResource> relatedResources) {
    this.relatedResources = relatedResources;
    return this;
  }

  public QuotaCost addRelatedResourcesItem(RelatedResource relatedResourcesItem) {
    if (this.relatedResources == null) {
      this.relatedResources = new ArrayList<>();
    }
    this.relatedResources.add(relatedResourcesItem);
    return this;
  }

   /**
   * Get relatedResources
   * @return relatedResources
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RELATED_RESOURCES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<RelatedResource> getRelatedResources() {
    return relatedResources;
  }


  @JsonProperty(JSON_PROPERTY_RELATED_RESOURCES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRelatedResources(List<RelatedResource> relatedResources) {
    this.relatedResources = relatedResources;
  }


  public QuotaCost version(String version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVersion() {
    return version;
  }


  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVersion(String version) {
    this.version = version;
  }


  /**
   * Return true if this QuotaCost object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QuotaCost quotaCost = (QuotaCost) o;
    return Objects.equals(this.href, quotaCost.href) &&
        Objects.equals(this.id, quotaCost.id) &&
        Objects.equals(this.kind, quotaCost.kind) &&
        Objects.equals(this.allowed, quotaCost.allowed) &&
        Objects.equals(this.consumed, quotaCost.consumed) &&
        Objects.equals(this.organizationId, quotaCost.organizationId) &&
        Objects.equals(this.quotaId, quotaCost.quotaId) &&
        Objects.equals(this.relatedResources, quotaCost.relatedResources) &&
        Objects.equals(this.version, quotaCost.version);
  }

  @Override
  public int hashCode() {
    return Objects.hash(href, id, kind, allowed, consumed, organizationId, quotaId, relatedResources, version);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QuotaCost {\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    allowed: ").append(toIndentedString(allowed)).append("\n");
    sb.append("    consumed: ").append(toIndentedString(consumed)).append("\n");
    sb.append("    organizationId: ").append(toIndentedString(organizationId)).append("\n");
    sb.append("    quotaId: ").append(toIndentedString(quotaId)).append("\n");
    sb.append("    relatedResources: ").append(toIndentedString(relatedResources)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

