/*
 * Account Management Service API
 * Manage user subscriptions and clusters
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.redhat.services.ffm.amsclient.models;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.redhat.services.ffm.amsclient.models.ObjectReference;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * RoleBindingAllOf
 */
@JsonPropertyOrder({
  RoleBindingAllOf.JSON_PROPERTY_ACCOUNT,
  RoleBindingAllOf.JSON_PROPERTY_CONFIG_MANAGED,
  RoleBindingAllOf.JSON_PROPERTY_CREATED_AT,
  RoleBindingAllOf.JSON_PROPERTY_MANAGED_BY,
  RoleBindingAllOf.JSON_PROPERTY_ORGANIZATION,
  RoleBindingAllOf.JSON_PROPERTY_ROLE,
  RoleBindingAllOf.JSON_PROPERTY_SUBSCRIPTION,
  RoleBindingAllOf.JSON_PROPERTY_TYPE,
  RoleBindingAllOf.JSON_PROPERTY_UPDATED_AT
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-04-21T14:46:15.841437+02:00[Europe/Prague]")
public class RoleBindingAllOf {
  public static final String JSON_PROPERTY_ACCOUNT = "account";
  private ObjectReference account;

  public static final String JSON_PROPERTY_CONFIG_MANAGED = "config_managed";
  private Boolean configManaged;

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  private OffsetDateTime createdAt;

  /**
   * Gets or Sets managedBy
   */
  public enum ManagedByEnum {
    CONFIG("Config"),
    
    USER("User");

    private String value;

    ManagedByEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ManagedByEnum fromValue(String value) {
      for (ManagedByEnum b : ManagedByEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_MANAGED_BY = "managed_by";
  private ManagedByEnum managedBy;

  public static final String JSON_PROPERTY_ORGANIZATION = "organization";
  private ObjectReference organization;

  public static final String JSON_PROPERTY_ROLE = "role";
  private ObjectReference role;

  public static final String JSON_PROPERTY_SUBSCRIPTION = "subscription";
  private ObjectReference subscription;

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    APPLICATION("Application"),
    
    SUBSCRIPTION("Subscription"),
    
    ORGANIZATION("Organization");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  private TypeEnum type;

  public static final String JSON_PROPERTY_UPDATED_AT = "updated_at";
  private OffsetDateTime updatedAt;

  public RoleBindingAllOf() { 
  }

  public RoleBindingAllOf account(ObjectReference account) {
    this.account = account;
    return this;
  }

   /**
   * Get account
   * @return account
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ACCOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ObjectReference getAccount() {
    return account;
  }


  @JsonProperty(JSON_PROPERTY_ACCOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccount(ObjectReference account) {
    this.account = account;
  }


  public RoleBindingAllOf configManaged(Boolean configManaged) {
    this.configManaged = configManaged;
    return this;
  }

   /**
   * Get configManaged
   * @return configManaged
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CONFIG_MANAGED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getConfigManaged() {
    return configManaged;
  }


  @JsonProperty(JSON_PROPERTY_CONFIG_MANAGED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConfigManaged(Boolean configManaged) {
    this.configManaged = configManaged;
  }


  public RoleBindingAllOf createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public RoleBindingAllOf managedBy(ManagedByEnum managedBy) {
    this.managedBy = managedBy;
    return this;
  }

   /**
   * Get managedBy
   * @return managedBy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MANAGED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ManagedByEnum getManagedBy() {
    return managedBy;
  }


  @JsonProperty(JSON_PROPERTY_MANAGED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setManagedBy(ManagedByEnum managedBy) {
    this.managedBy = managedBy;
  }


  public RoleBindingAllOf organization(ObjectReference organization) {
    this.organization = organization;
    return this;
  }

   /**
   * Get organization
   * @return organization
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ORGANIZATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ObjectReference getOrganization() {
    return organization;
  }


  @JsonProperty(JSON_PROPERTY_ORGANIZATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrganization(ObjectReference organization) {
    this.organization = organization;
  }


  public RoleBindingAllOf role(ObjectReference role) {
    this.role = role;
    return this;
  }

   /**
   * Get role
   * @return role
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ROLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ObjectReference getRole() {
    return role;
  }


  @JsonProperty(JSON_PROPERTY_ROLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRole(ObjectReference role) {
    this.role = role;
  }


  public RoleBindingAllOf subscription(ObjectReference subscription) {
    this.subscription = subscription;
    return this;
  }

   /**
   * Get subscription
   * @return subscription
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SUBSCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ObjectReference getSubscription() {
    return subscription;
  }


  @JsonProperty(JSON_PROPERTY_SUBSCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubscription(ObjectReference subscription) {
    this.subscription = subscription;
  }


  public RoleBindingAllOf type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(TypeEnum type) {
    this.type = type;
  }


  public RoleBindingAllOf updatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  /**
   * Return true if this RoleBinding_allOf object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RoleBindingAllOf roleBindingAllOf = (RoleBindingAllOf) o;
    return Objects.equals(this.account, roleBindingAllOf.account) &&
        Objects.equals(this.configManaged, roleBindingAllOf.configManaged) &&
        Objects.equals(this.createdAt, roleBindingAllOf.createdAt) &&
        Objects.equals(this.managedBy, roleBindingAllOf.managedBy) &&
        Objects.equals(this.organization, roleBindingAllOf.organization) &&
        Objects.equals(this.role, roleBindingAllOf.role) &&
        Objects.equals(this.subscription, roleBindingAllOf.subscription) &&
        Objects.equals(this.type, roleBindingAllOf.type) &&
        Objects.equals(this.updatedAt, roleBindingAllOf.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(account, configManaged, createdAt, managedBy, organization, role, subscription, type, updatedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RoleBindingAllOf {\n");
    sb.append("    account: ").append(toIndentedString(account)).append("\n");
    sb.append("    configManaged: ").append(toIndentedString(configManaged)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    managedBy: ").append(toIndentedString(managedBy)).append("\n");
    sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    subscription: ").append(toIndentedString(subscription)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

