/*
 * Account Management Service API
 * Manage user subscriptions and clusters
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.redhat.services.ffm.amsclient.models;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * SelfTermsReview
 */
@JsonPropertyOrder({
  SelfTermsReview.JSON_PROPERTY_CHECK_OPTIONAL_TERMS,
  SelfTermsReview.JSON_PROPERTY_EVENT_CODE,
  SelfTermsReview.JSON_PROPERTY_SITE_CODE
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-04-21T14:46:15.841437+02:00[Europe/Prague]")
public class SelfTermsReview {
  public static final String JSON_PROPERTY_CHECK_OPTIONAL_TERMS = "check_optional_terms";
  private Boolean checkOptionalTerms = true;

  public static final String JSON_PROPERTY_EVENT_CODE = "event_code";
  private String eventCode;

  public static final String JSON_PROPERTY_SITE_CODE = "site_code";
  private String siteCode;

  public SelfTermsReview() { 
  }

  public SelfTermsReview checkOptionalTerms(Boolean checkOptionalTerms) {
    this.checkOptionalTerms = checkOptionalTerms;
    return this;
  }

   /**
   * Get checkOptionalTerms
   * @return checkOptionalTerms
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CHECK_OPTIONAL_TERMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCheckOptionalTerms() {
    return checkOptionalTerms;
  }


  @JsonProperty(JSON_PROPERTY_CHECK_OPTIONAL_TERMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCheckOptionalTerms(Boolean checkOptionalTerms) {
    this.checkOptionalTerms = checkOptionalTerms;
  }


  public SelfTermsReview eventCode(String eventCode) {
    this.eventCode = eventCode;
    return this;
  }

   /**
   * Get eventCode
   * @return eventCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_EVENT_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEventCode() {
    return eventCode;
  }


  @JsonProperty(JSON_PROPERTY_EVENT_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEventCode(String eventCode) {
    this.eventCode = eventCode;
  }


  public SelfTermsReview siteCode(String siteCode) {
    this.siteCode = siteCode;
    return this;
  }

   /**
   * Get siteCode
   * @return siteCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SITE_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSiteCode() {
    return siteCode;
  }


  @JsonProperty(JSON_PROPERTY_SITE_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSiteCode(String siteCode) {
    this.siteCode = siteCode;
  }


  /**
   * Return true if this SelfTermsReview object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SelfTermsReview selfTermsReview = (SelfTermsReview) o;
    return Objects.equals(this.checkOptionalTerms, selfTermsReview.checkOptionalTerms) &&
        Objects.equals(this.eventCode, selfTermsReview.eventCode) &&
        Objects.equals(this.siteCode, selfTermsReview.siteCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(checkOptionalTerms, eventCode, siteCode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SelfTermsReview {\n");
    sb.append("    checkOptionalTerms: ").append(toIndentedString(checkOptionalTerms)).append("\n");
    sb.append("    eventCode: ").append(toIndentedString(eventCode)).append("\n");
    sb.append("    siteCode: ").append(toIndentedString(siteCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

