/*
 * Account Management Service API
 * Manage user subscriptions and clusters
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.redhat.services.ffm.amsclient.models;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.redhat.services.ffm.amsclient.models.LandingPageCTLItem;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * SelfServiceLandingPageSchemaConfigTryLearn
 */
@JsonPropertyOrder({
  SelfServiceLandingPageSchemaConfigTryLearn.JSON_PROPERTY_CONFIGURE,
  SelfServiceLandingPageSchemaConfigTryLearn.JSON_PROPERTY_TRY
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-04-21T14:46:15.841437+02:00[Europe/Prague]")
public class SelfServiceLandingPageSchemaConfigTryLearn {
  public static final String JSON_PROPERTY_CONFIGURE = "configure";
  private List<LandingPageCTLItem> configure = null;

  public static final String JSON_PROPERTY_TRY = "try";
  private List<LandingPageCTLItem> _try = null;

  public SelfServiceLandingPageSchemaConfigTryLearn() { 
  }

  public SelfServiceLandingPageSchemaConfigTryLearn configure(List<LandingPageCTLItem> configure) {
    this.configure = configure;
    return this;
  }

  public SelfServiceLandingPageSchemaConfigTryLearn addConfigureItem(LandingPageCTLItem configureItem) {
    if (this.configure == null) {
      this.configure = new ArrayList<>();
    }
    this.configure.add(configureItem);
    return this;
  }

   /**
   * Get configure
   * @return configure
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CONFIGURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<LandingPageCTLItem> getConfigure() {
    return configure;
  }


  @JsonProperty(JSON_PROPERTY_CONFIGURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConfigure(List<LandingPageCTLItem> configure) {
    this.configure = configure;
  }


  public SelfServiceLandingPageSchemaConfigTryLearn _try(List<LandingPageCTLItem> _try) {
    this._try = _try;
    return this;
  }

  public SelfServiceLandingPageSchemaConfigTryLearn addTryItem(LandingPageCTLItem _tryItem) {
    if (this._try == null) {
      this._try = new ArrayList<>();
    }
    this._try.add(_tryItem);
    return this;
  }

   /**
   * Get _try
   * @return _try
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<LandingPageCTLItem> getTry() {
    return _try;
  }


  @JsonProperty(JSON_PROPERTY_TRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTry(List<LandingPageCTLItem> _try) {
    this._try = _try;
  }


  /**
   * Return true if this SelfServiceLandingPageSchema_configTryLearn object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SelfServiceLandingPageSchemaConfigTryLearn selfServiceLandingPageSchemaConfigTryLearn = (SelfServiceLandingPageSchemaConfigTryLearn) o;
    return Objects.equals(this.configure, selfServiceLandingPageSchemaConfigTryLearn.configure) &&
        Objects.equals(this._try, selfServiceLandingPageSchemaConfigTryLearn._try);
  }

  @Override
  public int hashCode() {
    return Objects.hash(configure, _try);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SelfServiceLandingPageSchemaConfigTryLearn {\n");
    sb.append("    configure: ").append(toIndentedString(configure)).append("\n");
    sb.append("    _try: ").append(toIndentedString(_try)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

