/*
 * Account Management Service API
 * Manage user subscriptions and clusters
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.redhat.services.ffm.amsclient.models;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * SkuRulesAllOf
 */
@JsonPropertyOrder({
  SkuRulesAllOf.JSON_PROPERTY_ALLOWED,
  SkuRulesAllOf.JSON_PROPERTY_QUOTA_ID,
  SkuRulesAllOf.JSON_PROPERTY_SKU
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-04-21T14:46:15.841437+02:00[Europe/Prague]")
public class SkuRulesAllOf {
  public static final String JSON_PROPERTY_ALLOWED = "allowed";
  private Integer allowed;

  public static final String JSON_PROPERTY_QUOTA_ID = "quota_id";
  private String quotaId;

  public static final String JSON_PROPERTY_SKU = "sku";
  private String sku;

  public SkuRulesAllOf() { 
  }

  public SkuRulesAllOf allowed(Integer allowed) {
    this.allowed = allowed;
    return this;
  }

   /**
   * Get allowed
   * @return allowed
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ALLOWED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAllowed() {
    return allowed;
  }


  @JsonProperty(JSON_PROPERTY_ALLOWED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAllowed(Integer allowed) {
    this.allowed = allowed;
  }


  public SkuRulesAllOf quotaId(String quotaId) {
    this.quotaId = quotaId;
    return this;
  }

   /**
   * Get quotaId
   * @return quotaId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_QUOTA_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getQuotaId() {
    return quotaId;
  }


  @JsonProperty(JSON_PROPERTY_QUOTA_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQuotaId(String quotaId) {
    this.quotaId = quotaId;
  }


  public SkuRulesAllOf sku(String sku) {
    this.sku = sku;
    return this;
  }

   /**
   * Get sku
   * @return sku
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SKU)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSku() {
    return sku;
  }


  @JsonProperty(JSON_PROPERTY_SKU)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSku(String sku) {
    this.sku = sku;
  }


  /**
   * Return true if this SkuRules_allOf object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SkuRulesAllOf skuRulesAllOf = (SkuRulesAllOf) o;
    return Objects.equals(this.allowed, skuRulesAllOf.allowed) &&
        Objects.equals(this.quotaId, skuRulesAllOf.quotaId) &&
        Objects.equals(this.sku, skuRulesAllOf.sku);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allowed, quotaId, sku);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SkuRulesAllOf {\n");
    sb.append("    allowed: ").append(toIndentedString(allowed)).append("\n");
    sb.append("    quotaId: ").append(toIndentedString(quotaId)).append("\n");
    sb.append("    sku: ").append(toIndentedString(sku)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

