/*
 * Account Management Service API
 * Manage user subscriptions and clusters
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.redhat.services.ffm.amsclient.models;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.redhat.services.ffm.amsclient.models.AccountReference;
import com.redhat.services.ffm.amsclient.models.ObjectReference;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * SubscriptionRoleBindingAllOf
 */
@JsonPropertyOrder({
  SubscriptionRoleBindingAllOf.JSON_PROPERTY_ACCOUNT,
  SubscriptionRoleBindingAllOf.JSON_PROPERTY_ACCOUNT_EMAIL,
  SubscriptionRoleBindingAllOf.JSON_PROPERTY_ACCOUNT_USERNAME,
  SubscriptionRoleBindingAllOf.JSON_PROPERTY_CREATED_AT,
  SubscriptionRoleBindingAllOf.JSON_PROPERTY_ROLE,
  SubscriptionRoleBindingAllOf.JSON_PROPERTY_SUBSCRIPTION,
  SubscriptionRoleBindingAllOf.JSON_PROPERTY_UPDATED_AT
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-04-21T14:46:15.841437+02:00[Europe/Prague]")
public class SubscriptionRoleBindingAllOf {
  public static final String JSON_PROPERTY_ACCOUNT = "account";
  private AccountReference account;

  public static final String JSON_PROPERTY_ACCOUNT_EMAIL = "account_email";
  private String accountEmail;

  public static final String JSON_PROPERTY_ACCOUNT_USERNAME = "account_username";
  private String accountUsername;

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_ROLE = "role";
  private ObjectReference role;

  public static final String JSON_PROPERTY_SUBSCRIPTION = "subscription";
  private ObjectReference subscription;

  public static final String JSON_PROPERTY_UPDATED_AT = "updated_at";
  private OffsetDateTime updatedAt;

  public SubscriptionRoleBindingAllOf() { 
  }

  public SubscriptionRoleBindingAllOf account(AccountReference account) {
    this.account = account;
    return this;
  }

   /**
   * Get account
   * @return account
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ACCOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AccountReference getAccount() {
    return account;
  }


  @JsonProperty(JSON_PROPERTY_ACCOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccount(AccountReference account) {
    this.account = account;
  }


  public SubscriptionRoleBindingAllOf accountEmail(String accountEmail) {
    this.accountEmail = accountEmail;
    return this;
  }

   /**
   * Get accountEmail
   * @return accountEmail
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ACCOUNT_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAccountEmail() {
    return accountEmail;
  }


  @JsonProperty(JSON_PROPERTY_ACCOUNT_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccountEmail(String accountEmail) {
    this.accountEmail = accountEmail;
  }


  public SubscriptionRoleBindingAllOf accountUsername(String accountUsername) {
    this.accountUsername = accountUsername;
    return this;
  }

   /**
   * Get accountUsername
   * @return accountUsername
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ACCOUNT_USERNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAccountUsername() {
    return accountUsername;
  }


  @JsonProperty(JSON_PROPERTY_ACCOUNT_USERNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccountUsername(String accountUsername) {
    this.accountUsername = accountUsername;
  }


  public SubscriptionRoleBindingAllOf createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public SubscriptionRoleBindingAllOf role(ObjectReference role) {
    this.role = role;
    return this;
  }

   /**
   * Get role
   * @return role
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ROLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ObjectReference getRole() {
    return role;
  }


  @JsonProperty(JSON_PROPERTY_ROLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRole(ObjectReference role) {
    this.role = role;
  }


  public SubscriptionRoleBindingAllOf subscription(ObjectReference subscription) {
    this.subscription = subscription;
    return this;
  }

   /**
   * Get subscription
   * @return subscription
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SUBSCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ObjectReference getSubscription() {
    return subscription;
  }


  @JsonProperty(JSON_PROPERTY_SUBSCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubscription(ObjectReference subscription) {
    this.subscription = subscription;
  }


  public SubscriptionRoleBindingAllOf updatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  /**
   * Return true if this SubscriptionRoleBinding_allOf object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubscriptionRoleBindingAllOf subscriptionRoleBindingAllOf = (SubscriptionRoleBindingAllOf) o;
    return Objects.equals(this.account, subscriptionRoleBindingAllOf.account) &&
        Objects.equals(this.accountEmail, subscriptionRoleBindingAllOf.accountEmail) &&
        Objects.equals(this.accountUsername, subscriptionRoleBindingAllOf.accountUsername) &&
        Objects.equals(this.createdAt, subscriptionRoleBindingAllOf.createdAt) &&
        Objects.equals(this.role, subscriptionRoleBindingAllOf.role) &&
        Objects.equals(this.subscription, subscriptionRoleBindingAllOf.subscription) &&
        Objects.equals(this.updatedAt, subscriptionRoleBindingAllOf.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(account, accountEmail, accountUsername, createdAt, role, subscription, updatedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubscriptionRoleBindingAllOf {\n");
    sb.append("    account: ").append(toIndentedString(account)).append("\n");
    sb.append("    accountEmail: ").append(toIndentedString(accountEmail)).append("\n");
    sb.append("    accountUsername: ").append(toIndentedString(accountUsername)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    subscription: ").append(toIndentedString(subscription)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

