/*
 * Account Management Service API
 * Manage user subscriptions and clusters
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.redhat.services.ffm.amsclient.models;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * SupportCasesRequest
 */
@JsonPropertyOrder({
  SupportCasesRequest.JSON_PROPERTY_ACCOUNT_NUMBER,
  SupportCasesRequest.JSON_PROPERTY_CASE_LANGUAGE,
  SupportCasesRequest.JSON_PROPERTY_CLUSTER_ID,
  SupportCasesRequest.JSON_PROPERTY_CLUSTER_UUID,
  SupportCasesRequest.JSON_PROPERTY_CONTACT_SSO_NAME,
  SupportCasesRequest.JSON_PROPERTY_DESCRIPTION,
  SupportCasesRequest.JSON_PROPERTY_EVENT_STREAM_ID,
  SupportCasesRequest.JSON_PROPERTY_OPENSHIFT_CLUSTER_ID,
  SupportCasesRequest.JSON_PROPERTY_PRODUCT,
  SupportCasesRequest.JSON_PROPERTY_SEVERITY,
  SupportCasesRequest.JSON_PROPERTY_SUBSCRIPTION_ID,
  SupportCasesRequest.JSON_PROPERTY_SUMMARY,
  SupportCasesRequest.JSON_PROPERTY_VERSION
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-04-21T14:46:15.841437+02:00[Europe/Prague]")
public class SupportCasesRequest {
  public static final String JSON_PROPERTY_ACCOUNT_NUMBER = "account_number";
  private String accountNumber;

  public static final String JSON_PROPERTY_CASE_LANGUAGE = "case_language";
  private String caseLanguage;

  public static final String JSON_PROPERTY_CLUSTER_ID = "cluster_id";
  private String clusterId;

  public static final String JSON_PROPERTY_CLUSTER_UUID = "cluster_uuid";
  private String clusterUuid;

  public static final String JSON_PROPERTY_CONTACT_SSO_NAME = "contact_sso_name";
  private String contactSsoName;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_EVENT_STREAM_ID = "event_stream_id";
  private String eventStreamId;

  public static final String JSON_PROPERTY_OPENSHIFT_CLUSTER_ID = "openshift_cluster_id";
  private String openshiftClusterId;

  public static final String JSON_PROPERTY_PRODUCT = "product";
  private String product = "OpenShift Container Platform";

  /**
   * Gets or Sets severity
   */
  public enum SeverityEnum {
    _1_URGENT_("1 (Urgent)"),
    
    _2_HIGH_("2 (High)"),
    
    _3_NORMAL_("3 (Normal)"),
    
    _4_LOW_("4 (Low)");

    private String value;

    SeverityEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static SeverityEnum fromValue(String value) {
      for (SeverityEnum b : SeverityEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_SEVERITY = "severity";
  private SeverityEnum severity;

  public static final String JSON_PROPERTY_SUBSCRIPTION_ID = "subscription_id";
  private String subscriptionId;

  public static final String JSON_PROPERTY_SUMMARY = "summary";
  private String summary;

  public static final String JSON_PROPERTY_VERSION = "version";
  private String version = "4.4";

  public SupportCasesRequest() { 
  }

  public SupportCasesRequest accountNumber(String accountNumber) {
    this.accountNumber = accountNumber;
    return this;
  }

   /**
   * Get accountNumber
   * @return accountNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ACCOUNT_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAccountNumber() {
    return accountNumber;
  }


  @JsonProperty(JSON_PROPERTY_ACCOUNT_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccountNumber(String accountNumber) {
    this.accountNumber = accountNumber;
  }


  public SupportCasesRequest caseLanguage(String caseLanguage) {
    this.caseLanguage = caseLanguage;
    return this;
  }

   /**
   * Get caseLanguage
   * @return caseLanguage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CASE_LANGUAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCaseLanguage() {
    return caseLanguage;
  }


  @JsonProperty(JSON_PROPERTY_CASE_LANGUAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCaseLanguage(String caseLanguage) {
    this.caseLanguage = caseLanguage;
  }


  public SupportCasesRequest clusterId(String clusterId) {
    this.clusterId = clusterId;
    return this;
  }

   /**
   * Get clusterId
   * @return clusterId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CLUSTER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getClusterId() {
    return clusterId;
  }


  @JsonProperty(JSON_PROPERTY_CLUSTER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClusterId(String clusterId) {
    this.clusterId = clusterId;
  }


  public SupportCasesRequest clusterUuid(String clusterUuid) {
    this.clusterUuid = clusterUuid;
    return this;
  }

   /**
   * Get clusterUuid
   * @return clusterUuid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CLUSTER_UUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getClusterUuid() {
    return clusterUuid;
  }


  @JsonProperty(JSON_PROPERTY_CLUSTER_UUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClusterUuid(String clusterUuid) {
    this.clusterUuid = clusterUuid;
  }


  public SupportCasesRequest contactSsoName(String contactSsoName) {
    this.contactSsoName = contactSsoName;
    return this;
  }

   /**
   * Get contactSsoName
   * @return contactSsoName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CONTACT_SSO_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getContactSsoName() {
    return contactSsoName;
  }


  @JsonProperty(JSON_PROPERTY_CONTACT_SSO_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContactSsoName(String contactSsoName) {
    this.contactSsoName = contactSsoName;
  }


  public SupportCasesRequest description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDescription(String description) {
    this.description = description;
  }


  public SupportCasesRequest eventStreamId(String eventStreamId) {
    this.eventStreamId = eventStreamId;
    return this;
  }

   /**
   * Get eventStreamId
   * @return eventStreamId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_EVENT_STREAM_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEventStreamId() {
    return eventStreamId;
  }


  @JsonProperty(JSON_PROPERTY_EVENT_STREAM_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEventStreamId(String eventStreamId) {
    this.eventStreamId = eventStreamId;
  }


  public SupportCasesRequest openshiftClusterId(String openshiftClusterId) {
    this.openshiftClusterId = openshiftClusterId;
    return this;
  }

   /**
   * Get openshiftClusterId
   * @return openshiftClusterId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_OPENSHIFT_CLUSTER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOpenshiftClusterId() {
    return openshiftClusterId;
  }


  @JsonProperty(JSON_PROPERTY_OPENSHIFT_CLUSTER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOpenshiftClusterId(String openshiftClusterId) {
    this.openshiftClusterId = openshiftClusterId;
  }


  public SupportCasesRequest product(String product) {
    this.product = product;
    return this;
  }

   /**
   * Get product
   * @return product
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PRODUCT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProduct() {
    return product;
  }


  @JsonProperty(JSON_PROPERTY_PRODUCT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProduct(String product) {
    this.product = product;
  }


  public SupportCasesRequest severity(SeverityEnum severity) {
    this.severity = severity;
    return this;
  }

   /**
   * Get severity
   * @return severity
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_SEVERITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public SeverityEnum getSeverity() {
    return severity;
  }


  @JsonProperty(JSON_PROPERTY_SEVERITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSeverity(SeverityEnum severity) {
    this.severity = severity;
  }


  public SupportCasesRequest subscriptionId(String subscriptionId) {
    this.subscriptionId = subscriptionId;
    return this;
  }

   /**
   * Get subscriptionId
   * @return subscriptionId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SUBSCRIPTION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSubscriptionId() {
    return subscriptionId;
  }


  @JsonProperty(JSON_PROPERTY_SUBSCRIPTION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubscriptionId(String subscriptionId) {
    this.subscriptionId = subscriptionId;
  }


  public SupportCasesRequest summary(String summary) {
    this.summary = summary;
    return this;
  }

   /**
   * Get summary
   * @return summary
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_SUMMARY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSummary() {
    return summary;
  }


  @JsonProperty(JSON_PROPERTY_SUMMARY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSummary(String summary) {
    this.summary = summary;
  }


  public SupportCasesRequest version(String version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVersion() {
    return version;
  }


  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVersion(String version) {
    this.version = version;
  }


  /**
   * Return true if this SupportCasesRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SupportCasesRequest supportCasesRequest = (SupportCasesRequest) o;
    return Objects.equals(this.accountNumber, supportCasesRequest.accountNumber) &&
        Objects.equals(this.caseLanguage, supportCasesRequest.caseLanguage) &&
        Objects.equals(this.clusterId, supportCasesRequest.clusterId) &&
        Objects.equals(this.clusterUuid, supportCasesRequest.clusterUuid) &&
        Objects.equals(this.contactSsoName, supportCasesRequest.contactSsoName) &&
        Objects.equals(this.description, supportCasesRequest.description) &&
        Objects.equals(this.eventStreamId, supportCasesRequest.eventStreamId) &&
        Objects.equals(this.openshiftClusterId, supportCasesRequest.openshiftClusterId) &&
        Objects.equals(this.product, supportCasesRequest.product) &&
        Objects.equals(this.severity, supportCasesRequest.severity) &&
        Objects.equals(this.subscriptionId, supportCasesRequest.subscriptionId) &&
        Objects.equals(this.summary, supportCasesRequest.summary) &&
        Objects.equals(this.version, supportCasesRequest.version);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountNumber, caseLanguage, clusterId, clusterUuid, contactSsoName, description, eventStreamId, openshiftClusterId, product, severity, subscriptionId, summary, version);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SupportCasesRequest {\n");
    sb.append("    accountNumber: ").append(toIndentedString(accountNumber)).append("\n");
    sb.append("    caseLanguage: ").append(toIndentedString(caseLanguage)).append("\n");
    sb.append("    clusterId: ").append(toIndentedString(clusterId)).append("\n");
    sb.append("    clusterUuid: ").append(toIndentedString(clusterUuid)).append("\n");
    sb.append("    contactSsoName: ").append(toIndentedString(contactSsoName)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    eventStreamId: ").append(toIndentedString(eventStreamId)).append("\n");
    sb.append("    openshiftClusterId: ").append(toIndentedString(openshiftClusterId)).append("\n");
    sb.append("    product: ").append(toIndentedString(product)).append("\n");
    sb.append("    severity: ").append(toIndentedString(severity)).append("\n");
    sb.append("    subscriptionId: ").append(toIndentedString(subscriptionId)).append("\n");
    sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

